services:
  satisfactory-server:
    build:
      context: .
    container_name: satisfactory-server
    restart: unless-stopped
    ports:
      - "7777:7777/tcp"
      - "7777:7777/udp"
      - "15000:15000/udp"
      - "15777:15777/udp"
    user: "999:999"
    volumes:
      - type: bind
        source: ./savegames
        target: /home/steam/.config/Epic/FactoryGame/Saved
    working_dir: /home/steam
    entrypoint:
      [
        "/home/steam/Satisfactory-dedicated/FactoryServer.sh",
        "-log",
        "-unattended",
        "-multihome=0.0.0.0",
      ]
